(load "~/.emacs.d/packages.el")
(load "~/.emacs.d/configs.el")
(load "~/.emacs.d/R.el")
(load "~/.emacs.d/bash.el")
(load "~/.emacs.d/python.el")
(load "~/.emacs.d/sql.el")
(load "~/.emacs.d/aliases.el")
(load "~/.emacs.d/projectile.el")
;;(load "~/.emacs.d/ruby.el")
(load "~/.emacs.d/pretty.el")
(load "~/.emacs.d/org.el")
(load "~/.emacs.d/env_vars.el")

